//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.WebAPI.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRStaffingModelConn : DbContext
    {
        public HRStaffingModelConn()
            : base("name=HRStaffingModelConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmploymentsType> EmploymentsType { get; set; }
        public virtual DbSet<JobsOffer> JobsOffer { get; set; }
        public virtual DbSet<JobTitles> JobTitles { get; set; }
        public virtual DbSet<LevelsStudy> LevelsStudy { get; set; }
        public virtual DbSet<JobIndustry> JobIndustry { get; set; }
        public virtual DbSet<CompanyServices> CompanyServices { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<AdminModules> AdminModules { get; set; }
        public virtual DbSet<JobsOfferApplication> JobsOfferApplication { get; set; }
    }
}
