//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.WebAPI.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsOffer
    {
        public int Id { get; set; }
        public Nullable<int> JobTitle { get; set; }
        public string Responsabilies { get; set; }
        public string Experience { get; set; }
        public Nullable<int> EmploymentTypeId { get; set; }
        public string Industry { get; set; }
        public Nullable<int> LevelStudyId { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
        public Nullable<int> ResponsibleId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual EmploymentsType EmploymentsType { get; set; }
        public virtual JobTitles JobTitles { get; set; }
        public virtual LevelsStudy LevelsStudy { get; set; }
    }
}
