//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.WebAPI.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations
    {
        public int Id { get; set; }
        public string LocationName { get; set; }
        public string LocationLatLon { get; set; }
        public bool IsPrincipal { get; set; }
        public string ConfgImagePin { get; set; }
    }
}
