//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.WebAPI.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications_JobsOfferApply
    {
        public int Id { get; set; }
        public int IdJobOfferApplication { get; set; }
        public bool NotificationSended { get; set; }
        public Nullable<System.DateTime> DateSend { get; set; }
        public Nullable<System.DateTime> DateCreted { get; set; }
    
        public virtual JobsOfferApplication JobsOfferApplication { get; set; }
    }
}
